
#Main settings
[main]
	#Local-Proxy address.For example: 127.0.0.1 .
	proxy_address = ""
	#Local-Proxy port.
	#Range: 0 ~ 65565
	proxy_port = 0
	#ImageCache max size.
	#Range: > 10
	cache_size = 100
	#Images max memory limit (byte).
	#Range: 1024 ~ 9223372036854775807
	image_memory_limit = 209715200
	#Image max size (byte).
	#Range: 1024 ~ 9223372036854775807
	image_size = 6291456
	#Max image count that will be render at one frame.
	#Range: > 1
	max_render_count = 50
	#Request total timeout limit (millisecond). Recommend: more than 1000ms on the internet.
	call_timeout = 2000
	#Custom User-Agent for downloading images. For example: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36", you can also get one from https://fake-useragent.herokuapp.com/browsers/0.1.8, provide by fake-agent
	custom_user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

